//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1320
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DM.Build.Yukon.DeployProperties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DM.Build.Yukon.DeployProperties.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag which indicates if altering an assembly, instead of creating one, in the database..
        /// </summary>
        internal static string asm_Alter_Txt {
            get {
                return ResourceManager.GetString("asm_Alter_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag indicating whether to drop tables (true) with columns dependent on UDT&apos;s/UDF&apos;s or just drop the column (False)..
        /// </summary>
        internal static string asm_Drop_Txt {
            get {
                return ResourceManager.GetString("asm_Drop_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name with which the assembly will be created in SQL Server. Change name when versioning an assembly..
        /// </summary>
        internal static string asm_Name_Txt {
            get {
                return ResourceManager.GetString("asm_Name_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the permissions the assembly will have in the database..
        /// </summary>
        internal static string asm_Perm_Txt {
            get {
                return ResourceManager.GetString("asm_Perm_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag indicating that persisted data for UDT&apos;s should not be validated when altering an assembly..
        /// </summary>
        internal static string asm_Unchecked_Txt {
            get {
                return ResourceManager.GetString("asm_Unchecked_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting to indicate whether to run in connected or disconnected mode..
        /// </summary>
        internal static string db_Connect_Txt {
            get {
                return ResourceManager.GetString("db_Connect_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection string to the SQL Server 2005 database where the assembly is to be created..
        /// </summary>
        internal static string db_ConnString_Txt {
            get {
                return ResourceManager.GetString("db_ConnString_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter information to connect to the Microsoft SQL Server 2005 you intend to deploy your project to..
        /// </summary>
        internal static string findDb_Descr_txt {
            get {
                return ResourceManager.GetString("findDb_Descr_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project file for your project (*.csproj|*.vbproj) can not be found. Click on the &apos;Browse&apos; button to search for it..
        /// </summary>
        internal static string fle_Proj_Txt {
            get {
                return ResourceManager.GetString("fle_Proj_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The deployment settings file (sql.proj), can not be found. Click on the &apos;Browse&apos; button to search for it.\n\nIf this is a project without a settings file, use the default &apos;sql.proj&apos; file. This can be found in the &apos;DeploymentProperties&apos; directory..
        /// </summary>
        internal static string fle_Sql_Txt {
            get {
                return ResourceManager.GetString("fle_Sql_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exits the dialog without updating anything..
        /// </summary>
        internal static string fndDb_Cancel_Txt {
            get {
                return ResourceManager.GetString("fndDb_Cancel_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either enter the database you want to deploy to, or click on the drop-down button to view available databases. You also have the ability to create a new database, by clicking on the &apos;New&apos; button..
        /// </summary>
        internal static string fndDb_Dbs_Txt {
            get {
                return ResourceManager.GetString("fndDb_Dbs_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new database on the selected server by clicking on this button..
        /// </summary>
        internal static string fndDb_NewDb_Txt {
            get {
                return ResourceManager.GetString("fndDb_NewDb_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a connection string from your selection and updates the Connection string box in the Deployment Properties dialog..
        /// </summary>
        internal static string fndDb_OK_Txt {
            get {
                return ResourceManager.GetString("fndDb_OK_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searches for servers on the network..
        /// </summary>
        internal static string fndDb_Refresh_Txt {
            get {
                return ResourceManager.GetString("fndDb_Refresh_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either enter the SQL server you want to deploy your project to, or select the server by clicking on the drop-down button. You can click the &apos;Refresh&apos; button to view servers on the network..
        /// </summary>
        internal static string fndDb_Servers_Txt {
            get {
                return ResourceManager.GetString("fndDb_Servers_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test the connection to the server/database..
        /// </summary>
        internal static string fndDb_Test_Txt {
            get {
                return ResourceManager.GetString("fndDb_Test_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag which indicates if the task is to infer (True) if a method is to be created as stored procedure/ UDF or base the creation on attributes (False). .
        /// </summary>
        internal static string meth_Infer_Txt {
            get {
                return ResourceManager.GetString("meth_Infer_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name (path to the file) of the prject file (*.vbproj/*.csproj)..
        /// </summary>
        internal static string proj_Project_Txt {
            get {
                return ResourceManager.GetString("proj_Project_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name (path to the file) which holds the settings for the deployment tasks..
        /// </summary>
        internal static string proj_Sql_Txt {
            get {
                return ResourceManager.GetString("proj_Sql_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What file extension the source files have..
        /// </summary>
        internal static string src_Ext_Txt {
            get {
                return ResourceManager.GetString("src_Ext_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to the source files..
        /// </summary>
        internal static string src_Path_txt {
            get {
                return ResourceManager.GetString("src_Path_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag which indicates if source files should be uploaded together with the assembly or not..
        /// </summary>
        internal static string src_Upload_Txt {
            get {
                return ResourceManager.GetString("src_Upload_Txt", resourceCulture);
            }
        }
    }
}
